# -*- coding: utf-8 -*-
"""ProjetoFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQIUT3PFmnBkLqOv43sNA9aGd0d_r5f8
"""

import sys


produtos = []
proximo_id = 1

def cadastrar_produto():
    global proximo_id
    print("\n--- Cadastrar Novo Produto ---")

    while True:
        nome = input("Digite o nome do produto: ").strip()
        if nome:
            break
        print("O nome do produto não pode ser vazio.")

    while True:
        try:
            preco = float(input("Digite o preço do produto (R$): "))
            if preco >= 0:
                break
            print("O preço não pode ser negativo.")
        except ValueError:
            print("Entrada inválida. Digite um número para o preço.")

    while True:
        try:
            estoque = int(input("Digite a quantidade em estoque: "))
            if estoque >= 0:
                break
            print("A quantidade em estoque não pode ser negativa.")
        except ValueError:
            print("Entrada inválida. Digite um número inteiro para o estoque.")

    novo_produto = {
        "id": proximo_id,
        "nome": nome,
        "preco": preco,
        "estoque": estoque
    }
    produtos.append(novo_produto)
    proximo_id += 1
    print(f"\n Produto '{nome}' cadastrado com sucesso! (ID: {novo_produto['id']})")

def listar_produtos():
    print("\n--- Lista de Produtos Cadastrados ---")
    if not produtos:
        print("Nenhum produto cadastrado.")
        return

    print("ID | Nome                       | Preço (R$) | Estoque")
    print("-" * 55)
    for produto in produtos:
        print(f"{produto['id']:<2} | {produto['nome']:<25} | R$ {produto['preco']:<8.2f} | {produto['estoque']:<7}")
    print("-" * 55)

def buscar_produto_por_id(id_produto):
    for produto in produtos:
        if produto["id"] == id_produto:
            return produto
    return None

def atualizar_produto():
    print("\n--- Atualizar Produto ---")
    if not produtos:
        print("Nenhum produto cadastrado para atualizar.")
        return

    listar_produtos()

    while True:
        try:
            id_atualizar = int(input("\nDigite o ID do produto que deseja atualizar: "))
            produto_encontrado = buscar_produto_por_id(id_atualizar)
            if produto_encontrado:
                break
            print(f"Produto com ID {id_atualizar} não encontrado.")
        except ValueError:
            print("Entrada inválida. Digite um ID numérico.")

    print(f"\nProduto selecionado: ID {produto_encontrado['id']} - {produto_encontrado['nome']}")
    print("Deixe em branco para manter o valor atual.")


    novo_nome = input(f"Novo nome (Atual: {produto_encontrado['nome']}): ").strip()
    if novo_nome:
        produto_encontrado['nome'] = novo_nome


    while True:
        novo_preco_str = input(f"Novo preço (Atual: R$ {produto_encontrado['preco']:.2f}): ").strip()
        if not novo_preco_str:
            break
        try:
            novo_preco = float(novo_preco_str)
            if novo_preco >= 0:
                produto_encontrado['preco'] = novo_preco
                break
            print("O preço não pode ser negativo.")
        except ValueError:
            print("Entrada inválida. Digite um número para o preço.")


    while True:
        novo_estoque_str = input(f"Nova quantidade em estoque (Atual: {produto_encontrado['estoque']}): ").strip()
        if not novo_estoque_str:
            break
        try:
            novo_estoque = int(novo_estoque_str)
            if novo_estoque >= 0:
                produto_encontrado['estoque'] = novo_estoque
                break
            print("A quantidade em estoque não pode ser negativa.")
        except ValueError:
            print("Entrada inválida. Digite um número inteiro para o estoque.")

    print(f"\n Produto ID {produto_encontrado['id']} atualizado com sucesso!")

def remover_produto():
    print("\n--- Remover Produto ---")
    if not produtos:
        print("Nenhum produto cadastrado para remover.")
        return

    listar_produtos()

    while True:
        try:
            id_remover = int(input("\nDigite o ID do produto que deseja remover: "))
            produto_encontrado = buscar_produto_por_id(id_remover)
            if produto_encontrado:
                break
            print(f"Produto com ID {id_remover} não encontrado.")
        except ValueError:
            print("Entrada inválida. Digite um ID numérico.")

    confirmacao = input(f"Tem certeza que deseja remover o produto '{produto_encontrado['nome']}' (ID: {id_remover})? (s/n): ").lower().strip()
    if confirmacao == 's':
        produtos.remove(produto_encontrado)
        print(f"\n Produto ID {id_remover} - '{produto_encontrado['nome']}' removido com sucesso!")
    else:
        print("\n Remoção cancelada.")

def gerar_relatorio():
    print("\n--- Relatório/Resumo de Estoque ---")
    if not produtos:
        print("Nenhum produto cadastrado para gerar o relatório.")
        return

    total_itens = len(produtos)
    total_estoque = sum(produto['estoque'] for produto in produtos)
    valor_total_estoque = sum(produto['preco'] * produto['estoque'] for produto in produtos)

    print(f"Total de produtos cadastrados: {total_itens}")
    print(f"Quantidade total de itens em estoque: {total_estoque}")
    print(f"Valor total do estoque (Preço * Estoque): R$ {valor_total_estoque:.2f}")

    if total_estoque > 0:
        estoque_medio = total_estoque / total_itens
        print(f"Estoque médio por produto: {estoque_medio:.2f} unidades")

def sair_sistema():
    print("\nEncerrando o Sistema. Obrigado por utilizar!")
    sys.exit()

def menu():
    while True:
        print("\n" + "=" * 40)
        print("  SISTEMA DE GERENCIAMENTO DE PRODUTOS")
        print("=" * 40)
        print("1. Cadastrar Produto ")
        print("2. Listar Produtos ")
        print("3. Atualizar Produto ")
        print("4. Remover Produto ")
        print("5. Gerar Relatório/Resumo")
        print("6. Sair do Programa")
        print("-" * 40)

        escolha = input("Escolha uma opção: ").strip()

        if escolha == '1':
            cadastrar_produto()
        elif escolha == '2':
            listar_produtos()
        elif escolha == '3':
            atualizar_produto()
        elif escolha == '4':
            remover_produto()
        elif escolha == '5':
            gerar_relatorio()
        elif escolha == '6':
            sair_sistema()
        else:
            print("\nOpção inválida. Por favor, escolha um número de 1 a 6.")


if __name__ == "__main__":
    menu()